# Generated by Django 6.0.7 on 2026-07-23 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='song_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='total_scrobbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='album_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='song_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='total_scrobbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='total_scrobbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='total_scrobbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.album'),
        ),
    ]
